### ISSUE TITLE
在登录已欠费用户时报错

### ISSUE THREAD

**Issue by kahuuchino** [iMyOwn/ipgw#43]
虽然不影响使用，但还是报一下吧
报错信息如下：
```
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/neucn/ipgw/pkg/handler.(*IpgwHandler).ParseBasicInfo(0xc000114330)
        github.com/neucn/ipgw/pkg/handler/ipgw.go:148 +0x20e
github.com/neucn/ipgw/pkg/handler.(*IpgwHandler).Login(0xc000114330, 0xc000100460)
        github.com/neucn/ipgw/pkg/handler/ipgw.go:62 +0x88
github.com/neucn/ipgw/pkg/cmd.login(0xc000114330, 0xc94aa9)
        github.com/neucn/ipgw/pkg/cmd/login.go:82 +0x46
github.com/neucn/ipgw/pkg/cmd.loginUseDefaultAccount(0xd1a858)
        github.com/neucn/ipgw/pkg/cmd/cmd.go:66 +0x1fa
github.com/neucn/ipgw/pkg/cmd.glob..func12(0xc0001646c0)
        github.com/neucn/ipgw/pkg/cmd/cmd.go:34 +0xc5
github.com/urfave/cli/v2.(*App).RunContext(0xf569c0, {0xd1a6d0, 0xc000128078}, {0xc0001041f0, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        ./main.go:10 +0x47
```
使用的账户在ip网关网页登录时显示用户已欠费

**Comment by amtoaer** [comment]
啊，这个问题的话我之前有发现，并且已经在[160d5db](https://github.com/neucn/ipgw/commit/160d5db55b3d6cdcf8f23d01473ba1a3076cd8cb)修复了，可能是白白忘记 release 了 XD

**Comment by unbyte** [comment]
之前没想到是panic了，还以为只涉及显示，今晚release吧😳
