### ISSUE TITLE
一网通办改版为一号通后，程序失效

### ISSUE THREAD

**Issue by chiyuki0325** [iMyOwn/ipgw#60]
```
using account '20245782'
login failed:
	Post "https://personal.neu.edu.cn/portal/": x509: certificate is not valid for any names, but wanted to match personal.neu.edu.cn
```

portal.neu.edu.cn 改版为 personal.neu.edu.cn 后程序已失效

**Comment by unbyte** [comment]
需要更改 https://github.com/neucn/neugo 适配新的一号通

**Comment by FeralLiu** [comment]
所以楼主打算解决吗

**Comment by stceum** [comment]
可以帮助解决，但是我使用我自己的账号和同学的账号测试均没有复现这个问题，我们的学号是 220xxxx
![image](https://github.com/user-attachments/assets/f27b719b-16eb-4360-9f55-684792e764ed)

**Comment by Neboer** [comment]
出现问题的同学可以试试其他的IPGW登录软件，看看是否还依然存在问题。最好能抓包比对一下以确认

**Comment by unbyte** [comment]
和信网办老师沟通后已知的信息：
1. 校园网门户和网关认证架构**正**在进行**大型**变更
2. 现在还很不稳定，因此短期内不太能有稳定的网关认证和账号信息获取的方式(推论)
3. 目前学校老师人力也很稀缺，没有精力来维护社区工具

**Comment by Neboer** [comment]
可以试试 [NEU-ipgw-manager](https://github.com/Neboer/ipgw-py-manager) 。

**Comment by FeralLiu** [comment]
> 可以试试 [NEU-ipgw-manager](https://github.com/Neboer/ipgw-py-manager) 。

我通过windows使用了这个程序，是成功的，但使用ubuntu  20.04系统，发现有如下报错,我用的是火狐浏览器：Traceback (most recent call last):
  File "/home/neuxxx/.local/bin/ipgw", line 8, in <module>
    sys.exit(main())
  File "/home/neuxxx/.local/lib/python3.8/site-packages/ipgw/cli/ipgw.py", line 36, in main
    main_ipgw = IPGW()
  File "/home/neuxxx/.local/lib/python3.8/site-packages/ipgw/core/ipgw.py", line 18, in __init__
    self.union_auth_page = SSO_prepare(self.sess)
  File "/home/neuxxx/.local/lib/python3.8/site-packages/ipgw/core/api/SSO.py", line 33, in SSO_prepare
    "form_lt_string": form.find("input", {'id': 'lt'}).attrs["value"],
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by Neboer** [comment]
请将issue报给 [NEU-ipgw-manager](https://github.com/Neboer/ipgw-py-manager)  而不是这里。
